# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 500)
        MainWindow.setMinimumSize(QtCore.QSize(600, 500))
        MainWindow.setMaximumSize(QtCore.QSize(600, 500))
        MainWindow.setStyleSheet("background: qlineargradient(\n"
"    x2:0, \n"
"    y1:0, \n"
"    x1:0, \n"
"    y1:1,\n"
"    stop:0 #404040,\n"
"    stop:1 #E6E6E6\n"
");")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
"<ui version=\"4.0\">\n"
" <widget name=\"__qt_fake_top_level\">\n"
"  <widget class=\"QWidget\" name=\"widget\" native=\"true\">\n"
"   <property name=\"geometry\">\n"
"    <rect>\n"
"     <x>10</x>\n"
"     <y>10</y>\n"
"     <width>841</width>\n"
"     <height>551</height>\n"
"    </rect>\n"
"   </property>\n"
"   <property name=\"sizePolicy\">\n"
"    <sizepolicy hsizetype=\"Expanding\" vsizetype=\"Expanding\">\n"
"     <horstretch>0</horstretch>\n"
"     <verstretch>0</verstretch>\n"
"    </sizepolicy>\n"
"   </property>\n"
"   <property name=\"minimumSize\">\n"
"    <size>\n"
"     <width>500</width>\n"
"     <height>500</height>\n"
"    </size>\n"
"   </property>\n"
"   <property name=\"layoutDirection\">\n"
"    <enum>Qt::LeftToRight</enum>\n"
"   </property>\n"
"   <property name=\"styleSheet\">\n"
"    <string notr=\"true\">background:transparent;</string>\n"
"   </property>\n"
"   <widget class=\"QWidget\" name=\"verticalLayoutWidget\">\n"
"    <property name=\"geometry\">\n"
"     <rect>\n"
"      <x>280</x>\n"
"      <y>180</y>\n"
"      <width>281</width>\n"
"      <height>311</height>\n"
"     </rect>\n"
"    </property>\n"
"    <layout class=\"QVBoxLayout\" name=\"verticalLayout\">\n"
"     <item>\n"
"      <widget class=\"QPushButton\" name=\"pushButton\">\n"
"       <property name=\"styleSheet\">\n"
"        <string notr=\"true\">QPushButton {\n"
"    background-color: #D96B6B;\n"
"    color: white;\n"
"    border-radius: 8px;\n"
"    padding: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #E07C7C;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #B85A5A;\n"
"}\n"
"\n"
"QPushButton:checked {\n"
"    background-color: #A94444;\n"
"    font-weight: bold;\n"
"}</string>\n"
"       </property>\n"
"       <property name=\"text\">\n"
"        <string>MENTOR MEETINGS</string>\n"
"       </property>\n"
"      </widget>\n"
"     </item>\n"
"     <item>\n"
"      <widget class=\"QPushButton\" name=\"pushButton_6\">\n"
"       <property name=\"styleSheet\">\n"
"        <string notr=\"true\">QPushButton {\n"
"    background-color: #D96B6B;\n"
"    color: white;\n"
"    border-radius: 8px;\n"
"    padding: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #E07C7C;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #B85A5A;\n"
"}\n"
"\n"
"QPushButton:checked {\n"
"    background-color: #A94444;\n"
"    font-weight: bold;\n"
"}</string>\n"
"       </property>\n"
"       <property name=\"text\">\n"
"        <string>APPLICATIONS</string>\n"
"       </property>\n"
"      </widget>\n"
"     </item>\n"
"     <item>\n"
"      <widget class=\"QPushButton\" name=\"pushButton_7\">\n"
"       <property name=\"styleSheet\">\n"
"        <string notr=\"true\">QPushButton {\n"
"    background-color: #D96B6B;\n"
"    color: white;\n"
"    border-radius: 8px;\n"
"    padding: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #E07C7C;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #B85A5A;\n"
"}\n"
"\n"
"QPushButton:checked {\n"
"    background-color: #A94444;\n"
"    font-weight: bold;\n"
"}</string>\n"
"       </property>\n"
"       <property name=\"text\">\n"
"        <string>INTERVIEWS</string>\n"
"       </property>\n"
"      </widget>\n"
"     </item>\n"
"     <item>\n"
"      <widget class=\"QPushButton\" name=\"pushButton_8\">\n"
"       <property name=\"styleSheet\">\n"
"        <string notr=\"true\">QPushButton {\n"
"    background-color: #D96B6B;\n"
"    color: white;\n"
"    border-radius: 8px;\n"
"    padding: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #E07C7C;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #B85A5A;\n"
"}\n"
"\n"
"QPushButton:checked {\n"
"    background-color: #A94444;\n"
"    font-weight: bold;\n"
"}</string>\n"
"       </property>\n"
"       <property name=\"text\">\n"
"        <string>MAIN MENU</string>\n"
"       </property>\n"
"      </widget>\n"
"     </item>\n"
"     <item>\n"
"      <widget class=\"QPushButton\" name=\"pushButton_9\">\n"
"       <property name=\"styleSheet\">\n"
"        <string notr=\"true\">QPushButton {\n"
"    background-color: #D96B6B;\n"
"    color: white;\n"
"    border-radius: 8px;\n"
"    padding: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #E07C7C;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #B85A5A;\n"
"}\n"
"\n"
"QPushButton:checked {\n"
"    background-color: #A94444;\n"
"    font-weight: bold;\n"
"}</string>\n"
"       </property>\n"
"       <property name=\"text\">\n"
"        <string>EXIT</string>\n"
"       </property>\n"
"      </widget>\n"
"     </item>\n"
"    </layout>\n"
"   </widget>\n"
"   <widget class=\"QLabel\" name=\"label\">\n"
"    <property name=\"geometry\">\n"
"     <rect>\n"
"      <x>210</x>\n"
"      <y>70</y>\n"
"      <width>391</width>\n"
"      <height>101</height>\n"
"     </rect>\n"
"    </property>\n"
"    <property name=\"text\">\n"
"     <string/>\n"
"    </property>\n"
"    <property name=\"pixmap\">\n"
"     <pixmap>/Users/esrademirturk/Downloads/logo.png</pixmap>\n"
"    </property>\n"
"    <property name=\"scaledContents\">\n"
"     <bool>true</bool>\n"
"    </property>\n"
"    <property name=\"alignment\">\n"
"     <set>Qt::AlignCenter</set>\n"
"    </property>\n"
"   </widget>\n"
"  </widget>\n"
" </widget>\n"
" <resources/>\n"
"</ui>\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(-30, 0, 661, 500))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QtCore.QSize(500, 500))
        self.widget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.widget.setStyleSheet("background:transparent;")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(140, 70, 391, 101))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("logo.png"))
        self.label.setScaledContents(True)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.widget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(180, 190, 321, 201))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lbl_username = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.lbl_username.setStyleSheet("   background-color: white;\n"
"    color: black;\n"
"    border-radius: 8px;\n"
"    padding: 10px;\n"
"    border: 2px solid #D96B6B;")
        self.lbl_username.setObjectName("lbl_username")
        self.verticalLayout_2.addWidget(self.lbl_username)
        self.lbl_password = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.lbl_password.setStyleSheet("   background-color: white;\n"
"    color: black;\n"
"    border-radius: 8px;\n"
"    padding: 10px;\n"
"    border: 2px solid #D96B6B;")
        self.lbl_password.setObjectName("lbl_password")
        self.verticalLayout_2.addWidget(self.lbl_password)
        self.lbl_allert = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.lbl_allert.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_allert.setObjectName("lbl_allert")
        self.verticalLayout_2.addWidget(self.lbl_allert)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_sign_up = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.btn_sign_up.setStyleSheet("QPushButton {\n"
"    background-color: #D96B6B;\n"
"    color: white;\n"
"    border-radius: 8px;\n"
"    padding: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #E07C7C;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #B85A5A;\n"
"}\n"
"\n"
"QPushButton:checked {\n"
"    background-color: #A94444;\n"
"    font-weight: bold;\n"
"}")
        self.btn_sign_up.setObjectName("btn_sign_up")
        self.horizontalLayout.addWidget(self.btn_sign_up)
        self.btn_sign_in = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.btn_sign_in.setStyleSheet("QPushButton {\n"
"    background-color: #D96B6B;\n"
"    color: white;\n"
"    border-radius: 8px;\n"
"    padding: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #E07C7C;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #B85A5A;\n"
"}\n"
"\n"
"QPushButton:checked {\n"
"    background-color: #A94444;\n"
"    font-weight: bold;\n"
"}")
        self.btn_sign_in.setObjectName("btn_sign_in")
        self.horizontalLayout.addWidget(self.btn_sign_in)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.lbl_forgot_password = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.lbl_forgot_password.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_forgot_password.setOpenExternalLinks(False)
        self.lbl_forgot_password.setObjectName("lbl_forgot_password")
        self.verticalLayout_2.addWidget(self.lbl_forgot_password)
        self.check_show_password = QtWidgets.QCheckBox(self.widget)
        self.check_show_password.setGeometry(QtCore.QRect(510, 250, 86, 21))
        self.check_show_password.setObjectName("check_show_password")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "LOGIN"))
        self.lbl_username.setText(_translate("MainWindow", "Username"))
        self.lbl_password.setText(_translate("MainWindow", "Password"))
        self.lbl_allert.setText(_translate("MainWindow", "Your email or password is incorrect"))
        self.btn_sign_up.setText(_translate("MainWindow", "Sign Up"))
        self.btn_sign_in.setText(_translate("MainWindow", "Sign In"))
        self.lbl_forgot_password.setText(_translate("MainWindow", "Forgot password?"))
        self.check_show_password.setText(_translate("MainWindow", "Show"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
