# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'preferences_admin.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setMaximumSize(QtCore.QSize(800, 600))
        MainWindow.setStyleSheet("background: qlineargradient(\n"
"    x2:0, \n"
"    y1:0, \n"
"    x1:0, \n"
"    y1:1,\n"
"    stop:0 #404040,\n"
"    stop:1 #E6E6E6\n"
");")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, -10, 841, 591))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QtCore.QSize(500, 500))
        self.widget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.widget.setStyleSheet("background:transparent;")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(200, 70, 391, 101))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("logo.png"))
        self.label.setScaledContents(True)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.btn_mentor_interview = QtWidgets.QPushButton(self.widget)
        self.btn_mentor_interview.setGeometry(QtCore.QRect(270, 200, 281, 36))
        self.btn_mentor_interview.setStyleSheet("QPushButton {\n"
"    background-color: #D96B6B;\n"
"    color: white;\n"
"    border-radius: 8px;\n"
"    padding: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #E07C7C;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #B85A5A;\n"
"}\n"
"\n"
"QPushButton:checked {\n"
"    background-color: #A94444;\n"
"    font-weight: bold;\n"
"}")
        self.btn_mentor_interview.setObjectName("btn_mentor_interview")
        self.btn_admin_menu = QtWidgets.QPushButton(self.widget)
        self.btn_admin_menu.setGeometry(QtCore.QRect(270, 350, 281, 36))
        self.btn_admin_menu.setStyleSheet("QPushButton {\n"
"    background-color: #D96B6B;\n"
"    color: white;\n"
"    border-radius: 8px;\n"
"    padding: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #E07C7C;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #B85A5A;\n"
"}\n"
"\n"
"QPushButton:checked {\n"
"    background-color: #A94444;\n"
"    font-weight: bold;\n"
"}")
        self.btn_admin_menu.setObjectName("btn_admin_menu")
        self.btn_interview = QtWidgets.QPushButton(self.widget)
        self.btn_interview.setGeometry(QtCore.QRect(270, 250, 281, 36))
        self.btn_interview.setStyleSheet("QPushButton {\n"
"    background-color: #D96B6B;\n"
"    color: white;\n"
"    border-radius: 8px;\n"
"    padding: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #E07C7C;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #B85A5A;\n"
"}\n"
"\n"
"QPushButton:checked {\n"
"    background-color: #A94444;\n"
"    font-weight: bold;\n"
"}")
        self.btn_interview.setObjectName("btn_interview")
        self.btn_main_menu = QtWidgets.QPushButton(self.widget)
        self.btn_main_menu.setGeometry(QtCore.QRect(270, 400, 281, 36))
        self.btn_main_menu.setStyleSheet("QPushButton {\n"
"    background-color: #D96B6B;\n"
"    color: white;\n"
"    border-radius: 8px;\n"
"    padding: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #E07C7C;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #B85A5A;\n"
"}\n"
"\n"
"QPushButton:checked {\n"
"    background-color: #A94444;\n"
"    font-weight: bold;\n"
"}")
        self.btn_main_menu.setObjectName("btn_main_menu")
        self.btn_exit = QtWidgets.QPushButton(self.widget)
        self.btn_exit.setGeometry(QtCore.QRect(270, 450, 281, 36))
        self.btn_exit.setStyleSheet("QPushButton {\n"
"    background-color: #D96B6B;\n"
"    color: white;\n"
"    border-radius: 8px;\n"
"    padding: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #E07C7C;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #B85A5A;\n"
"}\n"
"\n"
"QPushButton:checked {\n"
"    background-color: #A94444;\n"
"    font-weight: bold;\n"
"}")
        self.btn_exit.setObjectName("btn_exit")
        self.btn_applications = QtWidgets.QPushButton(self.widget)
        self.btn_applications.setGeometry(QtCore.QRect(270, 300, 281, 36))
        self.btn_applications.setStyleSheet("QPushButton {\n"
"    background-color: #D96B6B;\n"
"    color: white;\n"
"    border-radius: 8px;\n"
"    padding: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #E07C7C;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #B85A5A;\n"
"}\n"
"\n"
"QPushButton:checked {\n"
"    background-color: #A94444;\n"
"    font-weight: bold;\n"
"}")
        self.btn_applications.setObjectName("btn_applications")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ADMIN PREFERENCES MENU"))
        self.btn_mentor_interview.setText(_translate("MainWindow", "MENTOR INTERVIEW"))
        self.btn_admin_menu.setText(_translate("MainWindow", "ADMIN MENU"))
        self.btn_interview.setText(_translate("MainWindow", "INTERVIEWS"))
        self.btn_main_menu.setText(_translate("MainWindow", "MAIN MENU"))
        self.btn_exit.setText(_translate("MainWindow", "EXIT"))
        self.btn_applications.setText(_translate("MainWindow", "APPLICATIONS"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
